### ISSUE TITLE
refreshList

### ISSUE THREAD

**Issue by EliasAamot** [fiLLLip/sheep-on-the-table#9]
Kanskje det berre er på mi maskin at refreshList er fitte treigt, men det hadde kanskje vori greit med ein pop-up-boks som seier "Waiting for the server to respond" mens ein ventar, så ein veit om det faktisk skjer arbeid, eller om programmet har klikka....

**Comment by fiLLLip** [comment]
Tror kanskje det er din pc.
http://dyn.filllip.net/screenshots/SNAG-0037.png

**Comment by EliasAamot** [comment]
Vi er enige om at det er pc'n min. Men når det skjer med PC'n min, kan det vel godt også skje med ein god del andre PC'ar?
